package policia360.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CalendarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioAllPropertiesEquals(Calendario expected, Calendario actual) {
        assertCalendarioAutoGeneratedPropertiesEquals(expected, actual);
        assertCalendarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioAllUpdatablePropertiesEquals(Calendario expected, Calendario actual) {
        assertCalendarioUpdatableFieldsEquals(expected, actual);
        assertCalendarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioAutoGeneratedPropertiesEquals(Calendario expected, Calendario actual) {
        assertThat(expected)
            .as("Verify Calendario auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioUpdatableFieldsEquals(Calendario expected, Calendario actual) {
        assertThat(expected)
            .as("Verify Calendario relevant properties")
            .satisfies(e -> assertThat(e.getFechaInicio()).as("check fechaInicio").isEqualTo(actual.getFechaInicio()))
            .satisfies(e -> assertThat(e.getFechaFin()).as("check fechaFin").isEqualTo(actual.getFechaFin()))
            .satisfies(e -> assertThat(e.getConcepto()).as("check concepto").isEqualTo(actual.getConcepto()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCalendarioUpdatableRelationshipsEquals(Calendario expected, Calendario actual) {
        assertThat(expected)
            .as("Verify Calendario relationships")
            .satisfies(e -> assertThat(e.getTrabajadores()).as("check trabajadores").isEqualTo(actual.getTrabajadores()));
    }
}
