package policia360.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CeldaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCeldaAllPropertiesEquals(Celda expected, Celda actual) {
        assertCeldaAutoGeneratedPropertiesEquals(expected, actual);
        assertCeldaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCeldaAllUpdatablePropertiesEquals(Celda expected, Celda actual) {
        assertCeldaUpdatableFieldsEquals(expected, actual);
        assertCeldaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCeldaAutoGeneratedPropertiesEquals(Celda expected, Celda actual) {
        assertThat(expected)
            .as("Verify Celda auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCeldaUpdatableFieldsEquals(Celda expected, Celda actual) {
        assertThat(expected)
            .as("Verify Celda relevant properties")
            .satisfies(e -> assertThat(e.getNumeroCamas()).as("check numeroCamas").isEqualTo(actual.getNumeroCamas()))
            .satisfies(e -> assertThat(e.getDisponibilidad()).as("check disponibilidad").isEqualTo(actual.getDisponibilidad()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCeldaUpdatableRelationshipsEquals(Celda expected, Celda actual) {}
}
