package policia360.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehiculoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAllPropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertVehiculoAutoGeneratedPropertiesEquals(expected, actual);
        assertVehiculoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAllUpdatablePropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertVehiculoUpdatableFieldsEquals(expected, actual);
        assertVehiculoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAutoGeneratedPropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(expected)
            .as("Verify Vehiculo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoUpdatableFieldsEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(expected)
            .as("Verify Vehiculo relevant properties")
            .satisfies(e -> assertThat(e.getIdentificador()).as("check identificador").isEqualTo(actual.getIdentificador()))
            .satisfies(e -> assertThat(e.getTipovehiculo()).as("check tipovehiculo").isEqualTo(actual.getTipovehiculo()))
            .satisfies(e -> assertThat(e.getDisponibilidad()).as("check disponibilidad").isEqualTo(actual.getDisponibilidad()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoUpdatableRelationshipsEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(expected)
            .as("Verify Vehiculo relationships")
            .satisfies(e -> assertThat(e.getTrabajadores()).as("check trabajadores").isEqualTo(actual.getTrabajadores()));
    }
}
